// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: store.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ECommerceStore_SearchProducts_FullMethodName = "/storeproto.ECommerceStore/SearchProducts"
	ECommerceStore_AddToCart_FullMethodName      = "/storeproto.ECommerceStore/AddToCart"
	ECommerceStore_GetOrderStatus_FullMethodName = "/storeproto.ECommerceStore/GetOrderStatus"
)

// ECommerceStoreClient is the client API for ECommerceStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The ECommerceStore service definition.
type ECommerceStoreClient interface {
	// Searches for products, streaming results back.
	SearchProducts(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Product], error)
	// Adds a product to a user's cart.
	AddToCart(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*Cart, error)
	// Retrieves the status of a specific order.
	GetOrderStatus(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderStatus, error)
}

type eCommerceStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewECommerceStoreClient(cc grpc.ClientConnInterface) ECommerceStoreClient {
	return &eCommerceStoreClient{cc}
}

func (c *eCommerceStoreClient) SearchProducts(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Product], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ECommerceStore_ServiceDesc.Streams[0], ECommerceStore_SearchProducts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, Product]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ECommerceStore_SearchProductsClient = grpc.ServerStreamingClient[Product]

func (c *eCommerceStoreClient) AddToCart(ctx context.Context, in *AddItemRequest, opts ...grpc.CallOption) (*Cart, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cart)
	err := c.cc.Invoke(ctx, ECommerceStore_AddToCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eCommerceStoreClient) GetOrderStatus(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatus)
	err := c.cc.Invoke(ctx, ECommerceStore_GetOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ECommerceStoreServer is the server API for ECommerceStore service.
// All implementations must embed UnimplementedECommerceStoreServer
// for forward compatibility.
//
// The ECommerceStore service definition.
type ECommerceStoreServer interface {
	// Searches for products, streaming results back.
	SearchProducts(*SearchRequest, grpc.ServerStreamingServer[Product]) error
	// Adds a product to a user's cart.
	AddToCart(context.Context, *AddItemRequest) (*Cart, error)
	// Retrieves the status of a specific order.
	GetOrderStatus(context.Context, *OrderRequest) (*OrderStatus, error)
	mustEmbedUnimplementedECommerceStoreServer()
}

// UnimplementedECommerceStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedECommerceStoreServer struct{}

func (UnimplementedECommerceStoreServer) SearchProducts(*SearchRequest, grpc.ServerStreamingServer[Product]) error {
	return status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedECommerceStoreServer) AddToCart(context.Context, *AddItemRequest) (*Cart, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedECommerceStoreServer) GetOrderStatus(context.Context, *OrderRequest) (*OrderStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderStatus not implemented")
}
func (UnimplementedECommerceStoreServer) mustEmbedUnimplementedECommerceStoreServer() {}
func (UnimplementedECommerceStoreServer) testEmbeddedByValue()                        {}

// UnsafeECommerceStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ECommerceStoreServer will
// result in compilation errors.
type UnsafeECommerceStoreServer interface {
	mustEmbedUnimplementedECommerceStoreServer()
}

func RegisterECommerceStoreServer(s grpc.ServiceRegistrar, srv ECommerceStoreServer) {
	// If the following call pancis, it indicates UnimplementedECommerceStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ECommerceStore_ServiceDesc, srv)
}

func _ECommerceStore_SearchProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ECommerceStoreServer).SearchProducts(m, &grpc.GenericServerStream[SearchRequest, Product]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ECommerceStore_SearchProductsServer = grpc.ServerStreamingServer[Product]

func _ECommerceStore_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECommerceStoreServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECommerceStore_AddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECommerceStoreServer).AddToCart(ctx, req.(*AddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ECommerceStore_GetOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ECommerceStoreServer).GetOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ECommerceStore_GetOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ECommerceStoreServer).GetOrderStatus(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ECommerceStore_ServiceDesc is the grpc.ServiceDesc for ECommerceStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ECommerceStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storeproto.ECommerceStore",
	HandlerType: (*ECommerceStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToCart",
			Handler:    _ECommerceStore_AddToCart_Handler,
		},
		{
			MethodName: "GetOrderStatus",
			Handler:    _ECommerceStore_GetOrderStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchProducts",
			Handler:       _ECommerceStore_SearchProducts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "store.proto",
}
